<table class="conferencer-agenda">
	<thead>
		<tr>
			<th></th>
			{{#tracks}}
				<th>{{.}}</th>
			{{/tracks}}
		</tr>
	</thead>
	<tbody>
		{{#timeslots}}
			<tr>
				<td>{{name}}</td>
				{{#tracks}}
					<td>
						{{#sessions}}
							<h2>{{title}}</h2>
							<h3>{{speaker}}</h3>
						{{/sessions}}
					</td>
				{{/tracks}}
			</tr>
		{{/timeslots}}
	</tbody>
</table>
